- name: Rotate distro passwords
  hosts: web
  become: yes
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Generate and apply distro user passwords
      set_fact:
        user_pw_map: "{{ user_pw_map | default({}) | combine({ item: lookup('password', '/dev/null length=22 chars=ascii_letters,digits') }) }}"
      loop: "{{ dist_users }}"

    - name: Show new Linux passwords
      debug:
        msg: "Linux user {{ item.key }}: {{ item.value }}"
      loop: "{{ user_pw_map | dict2items }}"

    - name: Apply Linux passwords
      user:
        name: "{{ item.key }}"
        password: "{{ item.value | password_hash('bcrypt') }}"
      loop: "{{ user_pw_map | dict2items }}"

- name: Rotate SQL passwords
  hosts: db
  become: yes
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Generate new SQL passwords
      set_fact:
        sql_pw_map: "{{ sql_pw_map | default({}) | combine({ item: lookup('password','/dev/null length=22 chars=ascii_letters,digits') }) }}"
      loop: "{{ sql_users }}"

    - name: Show new SQL passwords
      debug:
        msg: "SQL user {{ item.key }}: {{ item.value }}"
      loop: "{{ sql_pw_map | dict2items }}"

    - name: Apply wpuser password + grant all on wordpress DB
      mysql_user:
        name: wpuser
        password: "{{ sql_pw_map.wpuser }}"
        host: "%"
        priv: "wordpress.*:ALL"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Apply other SQL user passwords
      mysql_user:
        name: "{{ item.key }}"
        password: "{{ item.value }}"
        host: "%"
        priv: "*.*:USAGE"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
      loop: "{{ sql_pw_map | dict2items }}"
      when: item.key != 'wpuser'

    - name: Save wpuser password to fact
      set_fact:
        wpuser_password: "{{ sql_pw_map.wpuser }}"
